# Generated by Django 5.1.1 on 2024-09-24 10:06

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('ville', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('quartier', models.CharField(max_length=200)),
                ('nom_client', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('tel_whatsapp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('numero_devis', models.CharField(max_length=20, unique=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDevis.service')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
    ]
